export enum sizing {
    none = 0,
    borderWidth = 1,
    smallest = 4,
    smaller = 8,
    small = 12,
    normal = 16,
    mediumBig = 24,
    mediumBigger = 32,
    mediumBiggest = 48,
    big = 64,
    bigger = 96,
    biggest = 128,
    huge = 192,
    huger = 256,
}
